### ISSUE TITLE
`FileNotFoundError` when attempting to load model

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-nagl-models#3]
## Expected behavior ##

I expected to be able to use `GNNModel.load()` on one of the paths reported by `list_available_nagl_models`, but it's not finding the relevant file.

## Code to reproduce the behavior ##

``` python
>>> import pathlib
>>> from openff.nagl_models import validate_nagl_model_path, list_available_nagl_models
>>> from openff.nagl.nn._models import GNNModel
>>> list_available_nagl_models()
['openff-gnn-am1bcc-0.0.1-alpha.1.pt']
>>> pathlib.Path(validate_nagl_model_path(list_available_nagl_models()[0])).exists()
True
>>> GNNModel.load(list_available_nagl_models()[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mattthompson/mambaforge/envs/openff-interchange-env/lib/python3.10/site-packages/openff/nagl/nn/_models.py", line 265, in load
    model_kwargs = torch.load(model)
  File "/Users/mattthompson/mambaforge/envs/openff-interchange-env/lib/python3.10/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/mattthompson/mambaforge/envs/openff-interchange-env/lib/python3.10/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/mattthompson/mambaforge/envs/openff-interchange-env/lib/python3.10/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'openff-gnn-am1bcc-0.0.1-alpha.1.pt'
...

```

If I'm doing something obviously wrong, it would be nice to update the README to include how to actually load one of these models.

## Current environment ##

I found this in a development environment but can reproduce it in a fresh environment (`CONDA_SUBDIR=osx-64 mamba create -n nagl-model-issue -c conda-forge openff-nagl openff-nagl-models`)

```console
$ conda list openff
# packages in environment at /Users/mattthompson/mambaforge/envs/nagl-model-issue:
#
# Name                    Version                   Build  Channel
openff-amber-ff-ports     0.0.3              pyh6c4a22f_0    conda-forge
openff-forcefields        2023.02.1          pyh1a96a4e_0    conda-forge
openff-interchange        0.2.3              pyhd8ed1ab_1    conda-forge
openff-interchange-base   0.2.3              pyhd8ed1ab_1    conda-forge
openff-nagl               0.2.1              pyhd8ed1ab_0    conda-forge
openff-nagl-models        0.0.2              pyhd8ed1ab_0    conda-forge
openff-toolkit            0.12.1             pyhd8ed1ab_1    conda-forge
openff-toolkit-base       0.12.1             pyhd8ed1ab_1    conda-forge
openff-units              0.2.0              pyh1a96a4e_0    conda-forge
openff-utilities          0.1.8              pyh1a96a4e_0    conda-forge

**Comment by mattwthompson** [comment]
I _can_ load it from the absolute path but in my opinion that's not a great user experience, especially for those coming from `openff.toolkit.ForceField`'s loading machinery:
```python
>>> from openff.toolkit.typing.engines.smirnoff import ForceField, get_available_force_fields
>>> ForceField(get_available_force_fields()[-2])
<openff.toolkit.typing.engines.smirnoff.forcefield.ForceField object at 0x1a5140e50>
```

```python
>>> from openff.nagl.nn._models import GNNModel
/Users/mattthompson/mambaforge/envs/nagl-model-issue/lib/python3.10/site-packages/lightning_utilities/core/imports.py:13: UserWarning: Module openff was already imported from None, but /Users/mattthompson/software/openff-interchange is being added to sys.path
  import pkg_resources
>>> from openff.nagl_models import validate_nagl_model_path, list_available_nagl_models
>>> GNNModel.load(validate_nagl_model_path(list_available_nagl_models()[0]))
GNNModel(
  (convolution_module): ConvolutionModule(
    (gcn_layers): SAGEConvStack(
      (0): SAGEConv(
        (feat_drop): Dropout(p=0.01, inplace=False)
        (activation): ReLU()
        (fc_neigh): Linear(in_features=19, out_features=512, bias=False)
        (fc_self): Linear(in_features=19, out_features=512, bias=True)
      )
      (1): SAGEConv(
        (feat_drop): Dropout(p=0.01, inplace=False)
        (activation): ReLU()
        (fc_neigh): Linear(in_features=512, out_features=512, bias=False)
        (fc_self): Linear(in_features=512, out_features=512, bias=True)
      )
      (2): SAGEConv(
        (feat_drop): Dropout(p=0.01, inplace=False)
        (activation): ReLU()
        (fc_neigh): Linear(in_features=512, out_features=512, bias=False)
        (fc_self): Linear(in_features=512, out_features=512, bias=True)
      )
      (3): SAGEConv(
        (feat_drop): Dropout(p=0.01, inplace=False)
        (activation): ReLU()
        (fc_neigh): Linear(in_features=512, out_features=512, bias=False)
        (fc_self): Linear(in_features=512, out_features=512, bias=True)
      )
      (4): SAGEConv(
        (feat_drop): Dropout(p=0.01, inplace=False)
        (activation): ReLU()
        (fc_neigh): Linear(in_features=512, out_features=512, bias=False)
        (fc_self): Linear(in_features=512, out_features=512, bias=True)
      )
      (5): SAGEConv(
        (feat_drop): Dropout(p=0.01, inplace=False)
        (activation): ReLU()
        (fc_neigh): Linear(in_features=512, out_features=512, bias=False)
        (fc_self): Linear(in_features=512, out_features=512, bias=True)
      )
    )
  )
  (readout_modules): ModuleDict(
    (am1bcc-charges): ReadoutModule(
      (pooling_layer): PoolAtomFeatures()
      (readout_layers): SequentialLayers(
        (0): Linear(in_features=512, out_features=128, bias=True)
        (1): Sigmoid()
        (2): Dropout(p=0, inplace=False)
        (3): Linear(in_features=128, out_features=2, bias=True)
        (4): Identity()
        (5): Dropout(p=0, inplace=False)
      )
      (postprocess_layer): ComputePartialCharges()
    )
  )
)

**Comment by lilyminium** [comment]
Thanks for raising this @mattwthompson. That wasn't how `list_available_nagl_models` was intended to be used, but I can see the confusion with the analogous method in the toolkit. I've updated the method to return the full path in #5.
